version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_DB: django7
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db


