# Generated by Django 4.2.4 on 2023-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_habit_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение'),
        ),
    ]
